# Generated by Django 5.2.8 on 2026-01-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attachement',
            field=models.FileField(blank=True, upload_to='email_attachments/'),
        ),
    ]
