# Generated by Django 5.2.8 on 2026-01-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_email_attachement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='attachement',
            new_name='attachment',
        ),
    ]
