# Generated by Django 5.2.8 on 2026-01-13 17:07

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_rename_attachement_email_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body',
            field=CKEditor5Field()
        ),
    ]
